### ISSUE TITLE
The Process Sleeps Tonight_The Tokens Library

### ISSUE THREAD

**Issue by DukeHastMich** [EyeOfMidas/codeshanties#1]
ver .9b

&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
(async, await, async, await)
(async, await, async, await)
In the function, the mighty function
The child thread sleeps tonight
In the function, the delegate function
The process sleeps tonight
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
(async, await, async, await)
(async, await, async, await)
Near the far heap, the peaceful far heap
The child thread sleeps tonight
Near the far heap, the quiet far heap
The process sleeps tonight
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
(async, await, async, await)
(async, await, async, await)
Hush, my modal, don't Beep(), my modal
The process sleeps tonight
Hush, my modal, don't pop, my modal,
The process sleeps tonight
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A
(async, await, async, await)
(async, await, async, await)
(async, await, async, await)
(async, await, async, await)
&hee &hee &hee &hee 0dee &hee &hee &hee &hee word:A1 1 0 A

**Comment by EyeOfMidas** [comment]
Added in commit 83867d1a7b23f2665267a8382877b297be580abd

Thanks for this awesome song!
